apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f cloudtemp.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cloudflared
  name: cloudflared-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloudflared
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f cloudtemp.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - $(CLOUDFLARED_TOKEN)
          env:
            - name: CLOUDFLARED_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-secret
                  key: cloudflared-token
      restartPolicy: Always